version: '3.7'

services:

  figu-db-0:
    hostname: figu-db-0
    container_name: figu-db-0
    image: mongo:4
    ports:
      - "27017:27017"
    restart: always
    env_file:
      - .env
    networks:
      - mongo-net
    links:
      - figu-db-1:figu-db-1
      - figu-db-2:figu-db-2
    volumes:
      - "./scripts/setup.sh:/scripts/setup.sh"
      - "./scripts/file.key:/data/file.key"
    entrypoint: [ "/usr/bin/mongod", "--keyFile", "/data/file.key", "--replSet", "rs", "--journal", "--bind_ip_all" ]

  figu-db-1:
    hostname: figu-db-1
    container_name: figu-db-1
    image: mongo:4
    ports:
      - '27019:27017'
    restart: always
    networks:
      - mongo-net
    volumes:
      - "./scripts/file.key:/data/file.key"
    command: bash -c "/usr/bin/mongod --keyFile /data/file.key --replSet rs --journal --bind_ip_all"

  figu-db-2:
    hostname: figu-db-2
    container_name: figu-db-2
    image: mongo:4
    ports:
      - '27018:27017'
    restart: always
    networks:
      - mongo-net
    volumes:
      - "./scripts/file.key:/data/file.key"
    command: bash -c "/usr/bin/mongod --keyFile /data/file.key --replSet rs --journal --bind_ip_all"

networks:
  mongo-net:
    name: mongo-net
